### ISSUE TITLE
Content Update SS22

### ISSUE THREAD

**Issue by timfi** [fsi-tue/anfiheft#34]
### ToDo

- [x] update semester ticket price to `114.10€`
   [more details](https://www.naldo.de/tickets-und-preise/alle-fahrscheine/semesterticket/)
- [ ] update dates of in(tro)duction events
   <details>
     <summary>more details</summary>

     | Event            | Date       |
     | ---------------- |:---------- |
     | Wanderung        | 24.04.2022 |
     | Stadtrallye      | 20.04.2022 |
     | Kneipentour      | 20.04.2022 |
     | Spieleabend no°1 | 12.04.2022 |
     | Spieleabend no°2 | 28.04.2022 |
     | Grillen          | 13.04.2022 |
   </details>
- [x] ensure professor list is up to date
   [more details](https://uni-tuebingen.de/de/139980)
- [x] ensure *unikino* infos are up to date
   [more details](https://www.unifilm.de/studentenkinos/tuebingen)
- [x] ensure *hochschulsport* infos are up to date
   [more details](http://www.hsp.uni-tuebingen.de/)
- [x] ensure all links still work
- [x] ensure covid-disclaimers are up to date
- [x] change Ms. Weber to Ms. Georgatou
   > Prüfungsamt Bioinformatik / Medizininformatik
   > Rümelinstraße 23, Raum 709
   > 72070 Tübingen
   >
   [more details](https://uni-tuebingen.de/fakultaeten/mathematisch-naturwissenschaftliche-fakultaet/fachbereiche/informatik/studium/ansprechpartner-und-organisation/pruefungssekretariate/)
   - [x] replace text references
   - [x] remove from layout plan

**Comment by luoe** [comment]
Looks very good to me!

**Comment by PhictionalOne** [comment]
Timetables for the first three weeks are reintroduced in #36 
The time of the "Erstsemesterbegrüßung" is not yet known. Therefore a Draft PR.
