### ISSUE TITLE
Content Update WS22/23

### ISSUE THREAD

**Issue by timfi** [fsi-tue/anfiheft#44]
### ToDo

- [x] ensure semester ticket price is up to date
   [more details](https://www.naldo.de/tickets-und-preise/alle-fahrscheine/semesterticket/)
- [x] ensure professor list is up to date
   [more details](https://uni-tuebingen.de/de/139980)
- [x] ensure *unikino* infos are up to date
   [more details](https://www.unifilm.de/studentenkinos/tuebingen)
- [x] ensure *hochschulsport* infos are up to date
   [more details](http://www.hsp.uni-tuebingen.de/)
- [x] ensure all links still work
- [x] ensure covid-disclaimers are up to date
- [x] update dates of in(tro)duction events
   <details>
     <summary>more details</summary>

     | Event            | Date       |
     | ---------------- |:---------- |
     | Wanderung        | ??.??.???? |
     | Stadtrallye      | ??.??.???? |
     | Kneipentour      | ??.??.???? |
     | Spieleabend no°1 | ??.??.???? |
     | Spieleabend no°2 | ??.??.???? |
     | Grillen          | ??.??.???? |
   </details>
- [x] ensure this to-do list is complete 😉

**Comment by PhictionalOne** [comment]
- [ ] Do tasks mentioned in #43 
- [ ] Do tasks mentioned in #42 
- [ ] Do tasks mentioned in #37

**Comment by PhictionalOne** [comment]
- [ ] Also do #33

**Comment by PhictionalOne** [comment]
Done with #45
