### ISSUE TITLE
Content Update WS22/23

### ISSUE THREAD

**Issue by PhictionalOne** [fsi-tue/anfiheft#55]
# TODO

- [x] Ensure semester ticket price is up tod date
- [x] Check if the list of professors (`adressen.tex` & [Unipage](https://uni-tuebingen.de/de/139980))
- [x] Fetch new [Unikino](https://www.unifilm.de/studentenkinos/Tuebingen) program for `unikino.tex`
- [x] Check if Hochschulsport info is correct
- [x] Check all and every link if it still leads to its intended target
- [x] Update timetable in `die_ersten_wochen.tex`

# Partially done
See stuff in #54 and #53 

Also fix every grammar or spelling error you come across :grin:

**Comment by PhictionalOne** [comment]
@dakopen which of these did you already fix?

**Comment by dakopen** [comment]
I added the Germany Ticket and checked naldo but I also just saw that the JugendticketBW will become the GermanyTicket for Youth so I will add this as well. Also, I updated timetable for kogni but you can just copy and paste our events (like Kneipentour) as well as the Vorkurs. @PhictionalOne

**Comment by PhictionalOne** [comment]
@dakopen Is `studBeratung` for Kognis up to date?

**Comment by dakopen** [comment]
No, it should be `studienberatung@kogwis.uni-tuebingen.de`. Should I change it?

I will look into the other things from the list as well. @PhictionalOne
